# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim's Sandbox
email: tim.b.mccarter@gmail.com
description: Tim McCarter's personal sandbox. Soon to be filled with JavaScript and CSS goodness!
baseurl: "/sandbox" # the subpath of your site, e.g. /blog
url: "http://tmccarter.github.io/sandbox/" # the base hostname & protocol for your site
twitter_username: tbmccarter
github_username:  tmccarter

# Build settings
markdown: kramdown
